pull_request_rules:
  - name: Automatically merge Renovate PRs
    conditions:
      - author = renovate[bot]
      - check-success = trunk
      - check-success = check_image
    actions:
      queue:
      label:
        add:
          - dependencies
  - name: Automatically merge DeepSource Autofix PRs
    conditions:
      - author = deepsource-autofix[bot]
      - check-success = trunk
      - check-success = check_image
    actions:
      queue:
      label:
        add:
          - enhancement
queue_rules: []
