version: "1.1"
name: Status Check
env:
  host: localhost:7860
tests:
  app:
    steps:
      - name: GET request
        retries:
          count: 10
          interval: 10s
        http:
          url: http://${{env.host}}/
          method: GET
          timeout: 30s
          check:
            status: /^20/
