version: "1.1"
name: Status Check
env:
  host: 0.0.0.0:7860
tests:
  example:
    steps:
      - delay: 60s
      - name: GET request
        retries:
          count: 100
          interval: 10s
        http:
          url: http://${{env.host}}
          method: GET
          timeout: 30s
          check:
            status: /^20/
