services:
  vocalizr:
    image: ghcr.io/alphaspheredotai/vocalizr:multistage@sha256:d36ef9e6b0e0b5bd76c12acc0c2b0d4742b523d45956792bf12d3bc6b2315ecb
    ports:
      - "7860:7860"
    volumes:
      - virtualenv:/venv
    environment:
      - GRADIO_SERVER_PORT=7860
      - GRADIO_SERVER_NAME=0.0.0.0
volumes:
  virtualenv:
