services:
  vocalizr:
    image: ghcr.io/alphaspheredotai/vocalizr:latest
    ports:
      - "7860:7860"
    volumes:
      - huggingface_cache:/app/huggingface_model
    environment:
      - GRADIO_SERVER_PORT=7860
      - GRADIO_SERVER_NAME=0.0.0.0
