line-length = 88
indent-width = 4
target-version = "py310"

[lint]
select = ["ALL"]
ignore = ["D100", "D105", "D107", "D212", "D413", "SIM117"]
fixable = ["ALL"]
unfixable = []
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[lint.isort]
combine-as-imports = true

[lint.per-file-ignores]
"test_app.py" = ["INP001", "S101"]

[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "lf"
docstring-code-format = false
docstring-code-line-length = "dynamic"
