name: API Test
on: [push]
jobs:
  api_test:
    runs-on: ubuntu-latest
    name: API Tests
    steps:
      - name: Checkout 
        uses: actions/checkout@v3
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"
          activate-environment: true
      - name: Install the project
        run: uv sync --frozen
      - name: Run server 
        run: uv run src/vocalizr &
      - name: Step CI Action
        uses: stepci/stepci@v2
        with:
          workflow: ".github/stepci.yml"
