name: API Test
on: [push]
jobs:
  api_test:
    runs-on: ubuntu-latest
    name: API Tests
    steps:
      - name: Checkout 
        uses: actions/checkout@v3
      
      - name: Step CI Action
        uses: stepci/stepci@main
        with:
          workflow: ".github/stepci.yml"