name: API Test
on:
  push:
permissions:
  contents: read
jobs:
  api_test:
    runs-on: ubuntu-latest
    name: API Test
    services:
      vocalizr:
        image: ghcr.io/alphaspheredotai/vocalizr:154-merge
        ports:
          - 7860:7860
        options: >-
          --health-cmd "curl -o /dev/null -f -s -w 'Status: %{http_code},\tTime: %{time_total}s' http://localhost:7860/"
          --health-interval 10s
          --health-timeout 5s
          --health-start-period 15s
          --health-retries 15
    steps:
      - name: Echo URL
        run: echo "Vocalizr available on localhost:${{ job.services.vocalizr.ports['7860'] }}"
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.4.0
      - name: Setup Step CI
        run: npm install -g stepci
      - name: Run Step CI
        run: stepci run .github/stepci.yaml

