name: Code Quality
on:
  push:
    branches:
      - main
  pull_request:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true
permissions: read-all
jobs:
  format:
    name: Format
    runs-on: ubuntu-latest
    needs: compatibility
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          token: ${{ secrets.GH_TOKEN }}
          fetch-depth: 0
      - name: Install uv
        uses: astral-sh/setup-uv@7edac99f961f18b581bbd960d59d049f04c0002f # v6
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"
          activate-environment: true
      - name: Trunk install
        uses: trunk-io/trunk-action/setup@75699af9e26881e564e9d832ef7dc3af25ec031b # v1
      - name: Apply linters fixes if exist
        run: $TRUNK_PATH fmt --all --no-progress
      - name: Commit and push applied linter fixes
        uses: stefanzweifel/git-auto-commit-action@778341af668090896ca464160c2def5d1d1a3eb0 # v6
        if: success() || failure()
        with:
          commit_message: "[Trunk] Apply linters fixes"
  trunk:
    name: Trunk Code Quality
    runs-on: ubuntu-latest
    needs: format
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Install uv
        uses: astral-sh/setup-uv@7edac99f961f18b581bbd960d59d049f04c0002f # v6
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"
          activate-environment: true
      - name: Install the project
        run: uv sync --frozen
      - name: Trunk Code Quality
        uses: trunk-io/trunk-action@75699af9e26881e564e9d832ef7dc3af25ec031b # v1
  compatibility:
    name: Check Dependency Compatibility
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Install uv
        uses: astral-sh/setup-uv@7edac99f961f18b581bbd960d59d049f04c0002f # v6
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"
          activate-environment: true
      - name: Install the project
        run: uv sync --frozen --no-install-project
