name: Push to HuggingFace
on:
  push:
    branches:
      - main
  workflow_dispatch:
  release:
    types:
      - published
env:
  HF_HUB_ENABLE_HF_TRANSFER: "1"
  UV_FROZEN: "1"
  UV_LINK_MODE: "copy"
permissions: read-all
concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true
jobs:
  huggingface:
    name: Upload Vocalizr to HuggingFace Space
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - name: Install uv
        uses: astral-sh/setup-uv@4959332f0f014c5280e7eac8b70c90cb574c9f9b # v6
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"
          activate-environment: true
      - name: Install cli
        run: uv tool install huggingface-hub[cli,hf-transfer]
      - name: Remove Unnecessary Files
        run: |
          echo "*" > .gitignore
          echo "!.gitignore" >> .gitignore
          echo "!README.md" >> .gitignore
          echo "!Dockerfile" >> .gitignore
      - name: Add to git credentials
        run: git config --global credential.helper store
      - name: Login to HuggingFace Hub
        run: huggingface-cli login --add-to-git-credential --token ${{ secrets.HF_TOKEN }}
      - name: Check if logged in
        run: huggingface-cli whoami
      - name: Upload
        run: huggingface-cli upload AlphaSphereDotAI/Vocalizr . . --repo-type space
