name: Push to HuggingFace
on:
  push:
    branches:
      - main
  workflow_dispatch:
  release:
    types:
      - published
env:
  HF_HUB_ENABLE_HF_TRANSFER: "1"
  UV_FROZEN: "1"
  UV_LINK_MODE: "copy"
permissions: read-all
concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true
jobs:
  huggingface:
    name: Upload Vocalizr to HuggingFace Space
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Install uv
        uses: astral-sh/setup-uv@bd01e18f51369d5a26f1651c3cb451d3417e3bba # v6
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"
          activate-environment: true
      - name: Install cli
        run: uv tool install huggingface-hub[cli,hf-transfer]
      - name: Remove Unnecessary Files
        run: |
          echo "" >> .gitignore
          echo ".github/" >> .gitignore
          echo ".trunk/" >> .gitignore
          echo ".idea/" >> .gitignore
          echo "renovate.json" >> .gitignore
          echo ".deepsource.toml" >> .gitignore
          echo ".pre-commit-config.yaml" >> .gitignore
          echo "compose.yaml" >> .gitignore
      - name: Add to git credentials
        run: git config --global credential.helper store
      - name: Login to HuggingFace Hub
        run: huggingface-cli login --add-to-git-credential --token ${{ secrets.HF_TOKEN }}
      - name: Check if logged in
        run: huggingface-cli whoami
      - name: Upload
        run: huggingface-cli upload AlphaSphereDotAI/Vocalizr . . --repo-type space
