name: Upload Python Package
on:
  release:
    types:
      - published
permissions:
  contents: read
jobs:
  pypi-publish:
    name: Upload Python Package
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    environment:
      name: pypi
      url: https://pypi.org/project/vocalizr/${{ github.event.release.tag_name }}
    steps:
      - name: Retrieve release distributions
        uses: robinraju/release-downloader@daf26c55d821e836577a15f77d86ddc078948b05 # v1
        with:
          tag: ${{ github.event.release.tag_name }}
          out-file-path: dist/
          fileName: '*'
      - name: Publish release distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
